/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.VIEW;



import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Fatlind B. Hoxha
 */
public class AddPassenger extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddPassenger
     */
    public AddPassenger() {
        initComponents();
        autoID();
    }
   Connection con;
   PreparedStatement pst;
    String path=null;
    byte[] userimage=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPassengerPanel1 = new javax.swing.JPanel();
        nameAddPassengerLabel = new javax.swing.JLabel();
        lastNameAddPassengerLabel = new javax.swing.JLabel();
        passportIDAddPassengerLabel = new javax.swing.JLabel();
        addresAddPassengerLabel = new javax.swing.JLabel();
        nameAddPassengerTextField = new javax.swing.JTextField();
        lastNameAddPassengerTextField = new javax.swing.JTextField();
        passportIDAddPassengerFextField = new javax.swing.JTextField();
        addressTextFieldAP = new javax.swing.JTextField();
        passengerIDAddPassengerLabel = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        AddPassengerPanel2 = new javax.swing.JPanel();
        dateBirthAddPassengerLabel = new javax.swing.JLabel();
        genderAddPassengerLabel = new javax.swing.JLabel();
        contactAddPassengerLabel = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        contactAddPassengerTextField = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        photolabel = new javax.swing.JLabel();
        imageButtonAddPassanger = new javax.swing.JButton();
        addButtonAddPassenger = new javax.swing.JButton();
        cancelButtonAddPassenger = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1366, 801));

        AddPassengerPanel1.setBackground(new java.awt.Color(102, 204, 255));
        AddPassengerPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameAddPassengerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nameAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameAddPassengerLabel.setText("First Name");

        lastNameAddPassengerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lastNameAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameAddPassengerLabel.setText("Last Name");

        passportIDAddPassengerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        passportIDAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        passportIDAddPassengerLabel.setText("Passport ID");

        addresAddPassengerLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addresAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        addresAddPassengerLabel.setText("Address");

        javax.swing.GroupLayout AddPassengerPanel1Layout = new javax.swing.GroupLayout(AddPassengerPanel1);
        AddPassengerPanel1.setLayout(AddPassengerPanel1Layout);
        AddPassengerPanel1Layout.setHorizontalGroup(
            AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPassengerPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameAddPassengerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameAddPassengerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passportIDAddPassengerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addresAddPassengerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressTextFieldAP, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(nameAddPassengerTextField)
                    .addComponent(lastNameAddPassengerTextField)
                    .addComponent(passportIDAddPassengerFextField))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        AddPassengerPanel1Layout.setVerticalGroup(
            AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPassengerPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameAddPassengerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameAddPassengerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameAddPassengerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameAddPassengerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passportIDAddPassengerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passportIDAddPassengerFextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(AddPassengerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresAddPassengerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextFieldAP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        passengerIDAddPassengerLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        passengerIDAddPassengerLabel.setText("Passenger  ID");

        txtID.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtID.setForeground(new java.awt.Color(204, 0, 0));
        txtID.setText("jLabel1");

        AddPassengerPanel2.setBackground(new java.awt.Color(102, 204, 255));
        AddPassengerPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dateBirthAddPassengerLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dateBirthAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateBirthAddPassengerLabel.setText("Date of Birth");

        genderAddPassengerLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        genderAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderAddPassengerLabel.setText("Gender");

        contactAddPassengerLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contactAddPassengerLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactAddPassengerLabel.setText("Contact");

        r1.setText("Male");

        r2.setText("Female");

        javax.swing.GroupLayout AddPassengerPanel2Layout = new javax.swing.GroupLayout(AddPassengerPanel2);
        AddPassengerPanel2.setLayout(AddPassengerPanel2Layout);
        AddPassengerPanel2Layout.setHorizontalGroup(
            AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPassengerPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateBirthAddPassengerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderAddPassengerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactAddPassengerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPassengerPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(r2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPassengerPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r1)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactAddPassengerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        AddPassengerPanel2Layout.setVerticalGroup(
            AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPassengerPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateBirthAddPassengerLabel)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderAddPassengerLabel)
                    .addComponent(r1)
                    .addComponent(r2))
                .addGap(19, 19, 19)
                .addGroup(AddPassengerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactAddPassengerLabel)
                    .addComponent(contactAddPassengerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        photolabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imageButtonAddPassanger.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imageButtonAddPassanger.setText("Browse Image");
        imageButtonAddPassanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonAddPassangerActionPerformed(evt);
            }
        });

        addButtonAddPassenger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addButtonAddPassenger.setText("Add");
        addButtonAddPassenger.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 0), new java.awt.Color(0, 255, 0), new java.awt.Color(0, 255, 0), new java.awt.Color(153, 255, 102)));
        addButtonAddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAddPassengerActionPerformed(evt);
            }
        });

        cancelButtonAddPassenger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cancelButtonAddPassenger.setText("Cancel");
        cancelButtonAddPassenger.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(204, 0, 51)));
        cancelButtonAddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonAddPassengerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(passengerIDAddPassengerLabel)
                        .addGap(101, 101, 101)
                        .addComponent(txtID))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddPassengerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddPassengerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(photolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButtonAddPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addButtonAddPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imageButtonAddPassanger, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerIDAddPassengerLabel)
                    .addComponent(txtID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddPassengerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPassengerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(imageButtonAddPassanger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButtonAddPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButtonAddPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void autoID(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airticketmenagment","root","");
            Statement s = con.createStatement();
            ResultSet rs= s.executeQuery("select MAX(passengerID) from passenger");
            rs.next();
            rs.getString("MAX(passengerID)");
            if(rs.getString("MAX(passengerID)")== null){
                txtID.setText("PS001");
            }else{
                long passengerID = Long.parseLong(rs.getString("MAX(passengerID)").substring(2,rs.getString("MAX(passengerID)").length()));
               passengerID++;
               txtID.setText("PS"+ String.format("%03d", passengerID));
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddPassenger.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void cancelButtonAddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonAddPassengerActionPerformed
       this.hide();
    }//GEN-LAST:event_cancelButtonAddPassengerActionPerformed

    private void imageButtonAddPassangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonAddPassangerActionPerformed
      
                try {
        JFileChooser picchooser = new JFileChooser();
       picchooser.showOpenDialog(null);
       File pic = picchooser.getSelectedFile();       
       FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","png","jpg");
       picchooser.addChoosableFileFilter(filter);     
       path= pic.getAbsolutePath();
       BufferedImage img;                    
       img = ImageIO.read(picchooser.getSelectedFile());
       ImageIcon imageIcon = new ImageIcon(new
       ImageIcon(img).getImage().getScaledInstance(301, 180, Image.SCALE_DEFAULT));
              photolabel.setIcon(imageIcon); 
              
              
             File image = new File(path);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos= new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for(int readNum; (readNum=fis.read(buff)) !=-1 ; )
            {
                baos.write(buff,0,readNum);
            }
            userimage=baos.toByteArray();
              
              
              
        } catch (IOException ex) {
            Logger.getLogger(AddPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        
        
    }//GEN-LAST:event_imageButtonAddPassangerActionPerformed

    private void addButtonAddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAddPassengerActionPerformed
        
        String pId = txtID.getText();
         String fName = nameAddPassengerTextField.getText();
          String lName = lastNameAddPassengerTextField.getText();
           String pID = passportIDAddPassengerFextField.getText();
            String ads = addressTextFieldAP.getText();
            DateFormat da = new SimpleDateFormat("MM-dd-yyyy");
            String date =da.format(jDateChooser1.getDate());
            
            String gender ;
            if(r1.isSelected()){
                gender = "Male";
            }
            else
            {
                 gender = "Female";
            }
           String contact = contactAddPassengerTextField.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/airticketmenagment","root","");
              pst =con.prepareStatement("insert into passenger(passengerID,firstName,lastName,passportID,address,dateofBirth,gender,contact,photo)value(?,?,?,?,?,?,?,?,?)");
              pst.setString(1, pId);
              pst.setString(2, fName);
              pst.setString(3, lName);
              pst.setString(4, pID);
              pst.setString(5, ads);
              pst.setString(6, date);
              pst.setString(7, gender);
              pst.setString(8,  contact );
              pst.setBytes(9, userimage);
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "Registration Created");
              
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddPassenger.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        
        
        
    }//GEN-LAST:event_addButtonAddPassengerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPassengerPanel1;
    private javax.swing.JPanel AddPassengerPanel2;
    private javax.swing.JButton addButtonAddPassenger;
    private javax.swing.JLabel addresAddPassengerLabel;
    private javax.swing.JTextField addressTextFieldAP;
    private javax.swing.JButton cancelButtonAddPassenger;
    private javax.swing.JLabel contactAddPassengerLabel;
    private javax.swing.JTextField contactAddPassengerTextField;
    private javax.swing.JLabel dateBirthAddPassengerLabel;
    private javax.swing.JLabel genderAddPassengerLabel;
    private javax.swing.JButton imageButtonAddPassanger;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lastNameAddPassengerLabel;
    private javax.swing.JTextField lastNameAddPassengerTextField;
    private javax.swing.JLabel nameAddPassengerLabel;
    private javax.swing.JTextField nameAddPassengerTextField;
    private javax.swing.JLabel passengerIDAddPassengerLabel;
    private javax.swing.JTextField passportIDAddPassengerFextField;
    private javax.swing.JLabel passportIDAddPassengerLabel;
    private javax.swing.JLabel photolabel;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JLabel txtID;
    // End of variables declaration//GEN-END:variables
}
