/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.VIEW;

/**
 *
 * @author Fatlind B. Hoxha
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        PassangerMenu = new javax.swing.JMenu();
        AddPassengerMenuItem = new javax.swing.JMenuItem();
        SearchCostumerMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        TicketRegisterMenu = new javax.swing.JMenu();
        TicketRezervationMenyItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        FlightRegisterMenu = new javax.swing.JMenu();
        AddFlightMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        UserMenu = new javax.swing.JMenu();
        CreateUserMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 255, 255));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1366, 771));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        PassangerMenu.setText("Passanger");

        AddPassengerMenuItem.setText("Add Passanger");
        AddPassengerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengerMenuItemActionPerformed(evt);
            }
        });
        PassangerMenu.add(AddPassengerMenuItem);

        SearchCostumerMenuItem.setText("Search Costumer");
        SearchCostumerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCostumerMenuItemActionPerformed(evt);
            }
        });
        PassangerMenu.add(SearchCostumerMenuItem);

        jMenuItem2.setText("Passanger Report");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        PassangerMenu.add(jMenuItem2);

        jMenuBar1.add(PassangerMenu);

        TicketRegisterMenu.setText("Tickets Registration");

        TicketRezervationMenyItem.setText("Book Ticket");
        TicketRezervationMenyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketRezervationMenyItemActionPerformed(evt);
            }
        });
        TicketRegisterMenu.add(TicketRezervationMenyItem);

        jMenuItem1.setText("TicketReport");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        TicketRegisterMenu.add(jMenuItem1);

        jMenuBar1.add(TicketRegisterMenu);

        FlightRegisterMenu.setText("Flight Registration");

        AddFlightMenuItem.setText("Add Flight");
        AddFlightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightMenuItemActionPerformed(evt);
            }
        });
        FlightRegisterMenu.add(AddFlightMenuItem);

        jMenuItem3.setText("Flight Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        FlightRegisterMenu.add(jMenuItem3);

        jMenuBar1.add(FlightRegisterMenu);

        UserMenu.setText("User");

        CreateUserMenuItem.setText("Create User");
        CreateUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserMenuItemActionPerformed(evt);
            }
        });
        UserMenu.add(CreateUserMenuItem);

        jMenuBar1.add(UserMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserMenuItemActionPerformed
         userCreation uc = new userCreation();
        jDesktopPane1.add(uc);
        uc.setVisible(true);
    }//GEN-LAST:event_CreateUserMenuItemActionPerformed

    private void AddFlightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightMenuItemActionPerformed
          flightRegistration flight = new flightRegistration();
        jDesktopPane1.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_AddFlightMenuItemActionPerformed

    private void SearchCostumerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCostumerMenuItemActionPerformed
        searchPassanger passengerr = new searchPassanger();
        jDesktopPane1.add(passengerr);
        passengerr.setVisible(true);
    }//GEN-LAST:event_SearchCostumerMenuItemActionPerformed

    private void AddPassengerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengerMenuItemActionPerformed

        AddPassenger passenger = new AddPassenger();
        jDesktopPane1.add(passenger);
        passenger.setVisible(true);
    }//GEN-LAST:event_AddPassengerMenuItemActionPerformed

    private void TicketRezervationMenyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketRezervationMenyItemActionPerformed
        bookingTickets tickets = new bookingTickets();
        jDesktopPane1.add(tickets);
        tickets.setVisible(true);
    }//GEN-LAST:event_TicketRezervationMenyItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       ticketReport ticketr = new ticketReport();
        jDesktopPane1.add(ticketr);
        ticketr.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        passangerReport pr = new passangerReport();
        jDesktopPane1.add(pr);
        pr.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
         flightReport fr = new flightReport();
        jDesktopPane1.add(fr);
        fr.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddFlightMenuItem;
    private javax.swing.JMenuItem AddPassengerMenuItem;
    private javax.swing.JMenuItem CreateUserMenuItem;
    private javax.swing.JMenu FlightRegisterMenu;
    private javax.swing.JMenu PassangerMenu;
    private javax.swing.JMenuItem SearchCostumerMenuItem;
    private javax.swing.JMenu TicketRegisterMenu;
    private javax.swing.JMenuItem TicketRezervationMenyItem;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
